---
title: "ch1-3"
author: "Eliot Min"
date: "7/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(fpp3)

```

##Ch1

The predictability of an event or a quantity depends on several factors including:

how well we understand the factors that contribute to it;
how much data is available;
how similar the future is to the past;
whether the forecasts can affect the thing we are trying to forecast.


##Ch2

```{r}

y <- tsibble(
  Year = 2015:2019,
  Observation = c(123, 39, 78, 52, 110),
  index = Year
)

y

```

```{r}

#saving A10 so that we can use it for the rest of the chapter

PBS %>%
  filter(ATC2 == "A10") %>%
  select(Month, Concession, Type, Cost) %>%
  summarise(TotalC = sum(Cost)) %>%
  mutate(Cost = TotalC / 1e6) -> a10
```

```{r}

melsyd_economy <- ansett %>%
  filter(Airports == "MEL-SYD", Class == "Economy") %>%
  mutate(Passengers = Passengers/1000)
autoplot(melsyd_economy, Passengers) +
  labs(title = "Ansett airlines economy class",
       subtitle = "Melbourne-Sydney",
       y = "Passengers ('000)")

#relevant plotting functions: autoplot, gg_season(variable, labels) wraps a , gg_subseries(variable)

```

